### ISSUE TITLE
Examples when used with ignore schema are not documented

### ISSUE THREAD

**Issue by codeasashu** [myoperator/swagman#17]
Examples have __IGNOREPROP when used with ignore schema.
For example:

```yaml
responseExampleUsage:
      value:
        code: '200'
        message: __IGNOREPROPSWAGMAN
        status: success
```
