### ISSUE TITLE
Nested array not documented

### ISSUE THREAD

**Issue by codeasashu** [myoperator/swagman#7]
Right now, if postman json contains nested array, the generated schema only parses it to one level, documenting it to `string` type. For instance, consider this response json:

```json
{
    "key1": "val1",
    "item": [
    	{
    	    "prop1": "some value",
	    "nestedprop":  [{
	      "nestedprop1": "some another value"
	    }]
    	}
    ]
}
```

The generated schema is:

```yaml
components:
   schemas:
     ExampleResponseSchema:
       properties:
         key1:
           type: string
         item:
           items:
             nestedprop:
                type: string
           type: array
```

Which means the swagman isn't visiting internal nodes for nested props. Please fix
